"""initial migration for phase1 phase2-1 and evaluation_results

Revision ID: 0499a898e332
Revises: 
Create Date: 2026-04-23 15:33:40.791251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0499a898e332'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('model_type', sa.Enum('detection', 'action_detection', 'action_classification', 'classification', 'segmentation', name='ai_model_type'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_models'))
    )
    op.create_index('ix_ai_models_is_active', 'ai_models', ['is_active'], unique=False)
    op.create_index('ix_ai_models_model_type', 'ai_models', ['model_type'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('name', name=op.f('uq_roles_name'))
    )
    op.create_index('ix_roles_name', 'roles', ['name'], unique=False)
    op.create_table('sites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('floor_plan_image_path', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sites')),
    sa.UniqueConstraint('code', name=op.f('uq_sites_code')),
    sa.UniqueConstraint('name', name=op.f('uq_sites_name'))
    )
    op.create_index('ix_sites_code', 'sites', ['code'], unique=False)
    op.create_index('ix_sites_is_deleted', 'sites', ['is_deleted'], unique=False)
    op.create_index('ix_sites_name', 'sites', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('login_id', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('login_id', name=op.f('uq_users_login_id'))
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_index('ix_users_is_deleted', 'users', ['is_deleted'], unique=False)
    op.create_index('ix_users_login_id', 'users', ['login_id'], unique=False)
    op.create_table('alert_thresholds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.Enum('helmet_color', 'unauthorized_person', 'intrusion', 'custom', name='alert_type'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('threshold_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('threshold_unit', sa.String(length=20), nullable=True),
    sa.Column('color_value', sa.String(length=20), nullable=True),
    sa.Column('conditions', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_alert_thresholds_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_alert_thresholds_site_id_sites'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_thresholds'))
    )
    op.create_index('ix_alert_thresholds_alert_type', 'alert_thresholds', ['alert_type'], unique=False)
    op.create_index('ix_alert_thresholds_is_active', 'alert_thresholds', ['is_active'], unique=False)
    op.create_index('ix_alert_thresholds_site_id', 'alert_thresholds', ['site_id'], unique=False)
    op.create_table('datasets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('total_images', sa.Integer(), nullable=False),
    sa.Column('labeled_images', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_datasets_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_datasets'))
    )
    op.create_index('ix_datasets_is_active', 'datasets', ['is_active'], unique=False)
    op.create_index('ix_datasets_name', 'datasets', ['name'], unique=False)
    op.create_table('nvrs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('encrypted_password', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('online', 'offline', 'error', 'maintenance', name='device_status'), nullable=False),
    sa.Column('last_connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('firmware_version', sa.String(length=50), nullable=True),
    sa.Column('storage_capacity_gb', sa.Integer(), nullable=True),
    sa.Column('used_storage_gb', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_nvrs_site_id_sites'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nvrs'))
    )
    op.create_index('ix_nvrs_is_deleted', 'nvrs', ['is_deleted'], unique=False)
    op.create_index('ix_nvrs_site_id', 'nvrs', ['site_id'], unique=False)
    op.create_index('ix_nvrs_status', 'nvrs', ['status'], unique=False)
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_roles')),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_user_role')
    )
    op.create_index('ix_user_roles_role_id', 'user_roles', ['role_id'], unique=False)
    op.create_index('ix_user_roles_user_id', 'user_roles', ['user_id'], unique=False)
    op.create_table('cameras',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nvr_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('camera_code', sa.String(length=50), nullable=True),
    sa.Column('channel', sa.Integer(), nullable=True),
    sa.Column('rtsp_url', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('position_x', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('position_y', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('resolution', sa.String(length=20), nullable=True),
    sa.Column('fps', sa.Integer(), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('online', 'offline', 'error', 'maintenance', name='device_status'), nullable=False),
    sa.Column('last_connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['nvr_id'], ['nvrs.id'], name=op.f('fk_cameras_nvr_id_nvrs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_cameras_site_id_sites'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cameras')),
    sa.UniqueConstraint('camera_code', name=op.f('uq_cameras_camera_code'))
    )
    op.create_index('ix_cameras_camera_code', 'cameras', ['camera_code'], unique=False)
    op.create_index('ix_cameras_is_deleted', 'cameras', ['is_deleted'], unique=False)
    op.create_index('ix_cameras_nvr_id', 'cameras', ['nvr_id'], unique=False)
    op.create_index('ix_cameras_site_id', 'cameras', ['site_id'], unique=False)
    op.create_index('ix_cameras_status', 'cameras', ['status'], unique=False)
    op.create_table('training_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_name', sa.String(length=100), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', 'cancelled', name='training_job_status'), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_training_jobs_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_training_jobs_dataset_id_datasets')),
    sa.ForeignKeyConstraint(['model_id'], ['ai_models.id'], name=op.f('fk_training_jobs_model_id_ai_models'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_training_jobs'))
    )
    op.create_index('ix_training_jobs_dataset_id', 'training_jobs', ['dataset_id'], unique=False)
    op.create_index('ix_training_jobs_model_id', 'training_jobs', ['model_id'], unique=False)
    op.create_index('ix_training_jobs_status', 'training_jobs', ['status'], unique=False)
    op.create_table('alert_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=True),
    sa.Column('threshold_id', sa.Integer(), nullable=True),
    sa.Column('alert_type', sa.Enum('helmet_color', 'unauthorized_person', 'intrusion', 'custom', name='alert_type'), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='alert_severity'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('position_x', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('position_y', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('is_acknowledged', sa.Boolean(), nullable=False),
    sa.Column('acknowledged_by', sa.Integer(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], name=op.f('fk_alert_logs_acknowledged_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], name=op.f('fk_alert_logs_camera_id_cameras'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_alert_logs_site_id_sites'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['threshold_id'], ['alert_thresholds.id'], name=op.f('fk_alert_logs_threshold_id_alert_thresholds'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_logs'))
    )
    op.create_index('ix_alert_logs_alert_type', 'alert_logs', ['alert_type'], unique=False)
    op.create_index('ix_alert_logs_camera_id', 'alert_logs', ['camera_id'], unique=False)
    op.create_index('ix_alert_logs_detected_at', 'alert_logs', ['detected_at'], unique=False)
    op.create_index('ix_alert_logs_is_acknowledged', 'alert_logs', ['is_acknowledged'], unique=False)
    op.create_index('ix_alert_logs_severity', 'alert_logs', ['severity'], unique=False)
    op.create_index('ix_alert_logs_site_id', 'alert_logs', ['site_id'], unique=False)
    op.create_table('evaluation_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('training_job_id', sa.Integer(), nullable=True),
    sa.Column('evaluation_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mAP', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('precision', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('recall', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('f1_score', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('inference_time_ms', sa.Integer(), nullable=True),
    sa.Column('accuracy', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('source_file_path', sa.String(length=500), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('raw_metrics', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_evaluation_results_dataset_id_datasets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['model_id'], ['ai_models.id'], name=op.f('fk_evaluation_results_model_id_ai_models'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['training_job_id'], ['training_jobs.id'], name=op.f('fk_evaluation_results_training_job_id_training_jobs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluation_results'))
    )
    op.create_index('ix_evaluation_results_dataset_id', 'evaluation_results', ['dataset_id'], unique=False)
    op.create_index('ix_evaluation_results_evaluation_date', 'evaluation_results', ['evaluation_date'], unique=False)
    op.create_index('ix_evaluation_results_file_hash', 'evaluation_results', ['file_hash'], unique=False)
    op.create_index('ix_evaluation_results_is_processed', 'evaluation_results', ['is_processed'], unique=False)
    op.create_index('ix_evaluation_results_model_id', 'evaluation_results', ['model_id'], unique=False)
    op.create_index('ix_evaluation_results_training_job_id', 'evaluation_results', ['training_job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_evaluation_results_training_job_id', table_name='evaluation_results')
    op.drop_index('ix_evaluation_results_model_id', table_name='evaluation_results')
    op.drop_index('ix_evaluation_results_is_processed', table_name='evaluation_results')
    op.drop_index('ix_evaluation_results_file_hash', table_name='evaluation_results')
    op.drop_index('ix_evaluation_results_evaluation_date', table_name='evaluation_results')
    op.drop_index('ix_evaluation_results_dataset_id', table_name='evaluation_results')
    op.drop_table('evaluation_results')
    op.drop_index('ix_alert_logs_site_id', table_name='alert_logs')
    op.drop_index('ix_alert_logs_severity', table_name='alert_logs')
    op.drop_index('ix_alert_logs_is_acknowledged', table_name='alert_logs')
    op.drop_index('ix_alert_logs_detected_at', table_name='alert_logs')
    op.drop_index('ix_alert_logs_camera_id', table_name='alert_logs')
    op.drop_index('ix_alert_logs_alert_type', table_name='alert_logs')
    op.drop_table('alert_logs')
    op.drop_index('ix_training_jobs_status', table_name='training_jobs')
    op.drop_index('ix_training_jobs_model_id', table_name='training_jobs')
    op.drop_index('ix_training_jobs_dataset_id', table_name='training_jobs')
    op.drop_table('training_jobs')
    op.drop_index('ix_cameras_status', table_name='cameras')
    op.drop_index('ix_cameras_site_id', table_name='cameras')
    op.drop_index('ix_cameras_nvr_id', table_name='cameras')
    op.drop_index('ix_cameras_is_deleted', table_name='cameras')
    op.drop_index('ix_cameras_camera_code', table_name='cameras')
    op.drop_table('cameras')
    op.drop_index('ix_user_roles_user_id', table_name='user_roles')
    op.drop_index('ix_user_roles_role_id', table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index('ix_nvrs_status', table_name='nvrs')
    op.drop_index('ix_nvrs_site_id', table_name='nvrs')
    op.drop_index('ix_nvrs_is_deleted', table_name='nvrs')
    op.drop_table('nvrs')
    op.drop_index('ix_datasets_name', table_name='datasets')
    op.drop_index('ix_datasets_is_active', table_name='datasets')
    op.drop_table('datasets')
    op.drop_index('ix_alert_thresholds_site_id', table_name='alert_thresholds')
    op.drop_index('ix_alert_thresholds_is_active', table_name='alert_thresholds')
    op.drop_index('ix_alert_thresholds_alert_type', table_name='alert_thresholds')
    op.drop_table('alert_thresholds')
    op.drop_index('ix_users_login_id', table_name='users')
    op.drop_index('ix_users_is_deleted', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_sites_name', table_name='sites')
    op.drop_index('ix_sites_is_deleted', table_name='sites')
    op.drop_index('ix_sites_code', table_name='sites')
    op.drop_table('sites')
    op.drop_index('ix_roles_name', table_name='roles')
    op.drop_table('roles')
    op.drop_index('ix_ai_models_model_type', table_name='ai_models')
    op.drop_index('ix_ai_models_is_active', table_name='ai_models')
    op.drop_table('ai_models')
    # ### end Alembic commands ###
