"""phase2-2 labeling and annotation tables

Revision ID: 1771d1fdca57
Revises: 0499a898e332
Create Date: 2026-04-27 13:39:30.431554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1771d1fdca57'
down_revision: Union[str, Sequence[str], None] = '0499a898e332'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labeling_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', 'failed', name='labeling_task_status'), nullable=False),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('total_images', sa.Integer(), nullable=False),
    sa.Column('labeled_images', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], name=op.f('fk_labeling_tasks_assigned_to_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_labeling_tasks_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_labeling_tasks_dataset_id_datasets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_labeling_tasks'))
    )
    op.create_index('ix_labeling_tasks_assigned_to', 'labeling_tasks', ['assigned_to'], unique=False)
    op.create_index('ix_labeling_tasks_dataset_id', 'labeling_tasks', ['dataset_id'], unique=False)
    op.create_index('ix_labeling_tasks_is_deleted', 'labeling_tasks', ['is_deleted'], unique=False)
    op.create_index('ix_labeling_tasks_status', 'labeling_tasks', ['status'], unique=False)
    op.create_table('annotations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('labeling_task_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.Text(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('class_name', sa.String(length=100), nullable=False),
    sa.Column('bbox_x', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('bbox_y', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('bbox_width', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('bbox_height', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_annotations_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['labeling_task_id'], ['labeling_tasks.id'], name=op.f('fk_annotations_labeling_task_id_labeling_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_annotations'))
    )
    op.create_index('ix_annotations_class_id', 'annotations', ['class_id'], unique=False)
    op.create_index('ix_annotations_image_path', 'annotations', ['image_path'], unique=False)
    op.create_index('ix_annotations_is_deleted', 'annotations', ['is_deleted'], unique=False)
    op.create_index('ix_annotations_labeling_task_id', 'annotations', ['labeling_task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_annotations_labeling_task_id', table_name='annotations')
    op.drop_index('ix_annotations_is_deleted', table_name='annotations')
    op.drop_index('ix_annotations_image_path', table_name='annotations')
    op.drop_index('ix_annotations_class_id', table_name='annotations')
    op.drop_table('annotations')
    op.drop_index('ix_labeling_tasks_status', table_name='labeling_tasks')
    op.drop_index('ix_labeling_tasks_is_deleted', table_name='labeling_tasks')
    op.drop_index('ix_labeling_tasks_dataset_id', table_name='labeling_tasks')
    op.drop_index('ix_labeling_tasks_assigned_to', table_name='labeling_tasks')
    op.drop_table('labeling_tasks')
    # ### end Alembic commands ###
