"""phase3 mes processes efficiency worker detection

Revision ID: 75c7450f4406
Revises: f698d7366730
Create Date: 2026-04-28 17:52:50.944587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75c7450f4406'
down_revision: Union[str, Sequence[str], None] = 'f698d7366730'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mes_sync_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('processed_status', sa.Enum('pending', 'processing', 'success', 'failed', name='mes_sync_status'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_mes_sync_logs_site_id_sites'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mes_sync_logs'))
    )
    op.create_index('ix_mes_sync_logs_created_at', 'mes_sync_logs', ['created_at'], unique=False)
    op.create_index('ix_mes_sync_logs_processed_status', 'mes_sync_logs', ['processed_status'], unique=False)
    op.create_index('ix_mes_sync_logs_site_id', 'mes_sync_logs', ['site_id'], unique=False)
    op.create_table('processes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('line_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_processes_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_processes_site_id_sites'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processes')),
    sa.UniqueConstraint('site_id', 'code', name='uq_processes_site_code')
    )
    op.create_index('ix_processes_is_active', 'processes', ['is_active'], unique=False)
    op.create_index('ix_processes_is_deleted', 'processes', ['is_deleted'], unique=False)
    op.create_index('ix_processes_line_order', 'processes', ['line_order'], unique=False)
    op.create_index('ix_processes_site_id', 'processes', ['site_id'], unique=False)
    op.create_table('efficiency_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=False),
    sa.Column('mes_sync_log_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('shift', sa.Enum('day', 'evening', 'night', name='shift_type'), nullable=False),
    sa.Column('daily_production', sa.Integer(), nullable=True),
    sa.Column('hourly_production', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('worker_count', sa.Integer(), nullable=True),
    sa.Column('tact_time', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('standard_time', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('labor_productivity', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('lob', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('eb', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('capa_per_hr', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mes_sync_log_id'], ['mes_sync_logs.id'], name=op.f('fk_efficiency_metrics_mes_sync_log_id_mes_sync_logs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['process_id'], ['processes.id'], name=op.f('fk_efficiency_metrics_process_id_processes'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_efficiency_metrics'))
    )
    op.create_index('ix_efficiency_metrics_date', 'efficiency_metrics', ['date'], unique=False)
    op.create_index('ix_efficiency_metrics_date_process', 'efficiency_metrics', ['date', 'process_id'], unique=False)
    op.create_index('ix_efficiency_metrics_mes_sync_log_id', 'efficiency_metrics', ['mes_sync_log_id'], unique=False)
    op.create_index('ix_efficiency_metrics_process_id', 'efficiency_metrics', ['process_id'], unique=False)
    op.create_index('ix_efficiency_metrics_shift', 'efficiency_metrics', ['shift'], unique=False)
    op.create_table('process_flows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('floor_plan_image_path', sa.String(length=500), nullable=True),
    sa.Column('nodes', sa.JSON(), nullable=True),
    sa.Column('edges', sa.JSON(), nullable=True),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_process_flows_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['process_id'], ['processes.id'], name=op.f('fk_process_flows_process_id_processes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_process_flows')),
    sa.UniqueConstraint('process_id', 'version', name='uq_process_flows_process_version')
    )
    op.create_index('ix_process_flows_effective_from', 'process_flows', ['effective_from'], unique=False)
    op.create_index('ix_process_flows_is_active', 'process_flows', ['is_active'], unique=False)
    op.create_index('ix_process_flows_is_deleted', 'process_flows', ['is_deleted'], unique=False)
    op.create_index('ix_process_flows_process_id', 'process_flows', ['process_id'], unique=False)
    op.create_table('worker_detections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recognition_log_id', sa.Integer(), nullable=True),
    sa.Column('process_id', sa.Integer(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('worker_label', sa.String(length=100), nullable=True),
    sa.Column('entry_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exit_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], name=op.f('fk_worker_detections_camera_id_cameras'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['process_id'], ['processes.id'], name=op.f('fk_worker_detections_process_id_processes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recognition_log_id'], ['recognition_logs.id'], name=op.f('fk_worker_detections_recognition_log_id_recognition_logs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_worker_detections_site_id_sites'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_worker_detections'))
    )
    op.create_index('ix_worker_detections_camera_id', 'worker_detections', ['camera_id'], unique=False)
    op.create_index('ix_worker_detections_entry_time', 'worker_detections', ['entry_time'], unique=False)
    op.create_index('ix_worker_detections_process_id', 'worker_detections', ['process_id'], unique=False)
    op.create_index('ix_worker_detections_recognition_log_id', 'worker_detections', ['recognition_log_id'], unique=False)
    op.create_index('ix_worker_detections_site_id', 'worker_detections', ['site_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_worker_detections_site_id', table_name='worker_detections')
    op.drop_index('ix_worker_detections_recognition_log_id', table_name='worker_detections')
    op.drop_index('ix_worker_detections_process_id', table_name='worker_detections')
    op.drop_index('ix_worker_detections_entry_time', table_name='worker_detections')
    op.drop_index('ix_worker_detections_camera_id', table_name='worker_detections')
    op.drop_table('worker_detections')
    op.drop_index('ix_process_flows_process_id', table_name='process_flows')
    op.drop_index('ix_process_flows_is_deleted', table_name='process_flows')
    op.drop_index('ix_process_flows_is_active', table_name='process_flows')
    op.drop_index('ix_process_flows_effective_from', table_name='process_flows')
    op.drop_table('process_flows')
    op.drop_index('ix_efficiency_metrics_shift', table_name='efficiency_metrics')
    op.drop_index('ix_efficiency_metrics_process_id', table_name='efficiency_metrics')
    op.drop_index('ix_efficiency_metrics_mes_sync_log_id', table_name='efficiency_metrics')
    op.drop_index('ix_efficiency_metrics_date_process', table_name='efficiency_metrics')
    op.drop_index('ix_efficiency_metrics_date', table_name='efficiency_metrics')
    op.drop_table('efficiency_metrics')
    op.drop_index('ix_processes_site_id', table_name='processes')
    op.drop_index('ix_processes_line_order', table_name='processes')
    op.drop_index('ix_processes_is_deleted', table_name='processes')
    op.drop_index('ix_processes_is_active', table_name='processes')
    op.drop_table('processes')
    op.drop_index('ix_mes_sync_logs_site_id', table_name='mes_sync_logs')
    op.drop_index('ix_mes_sync_logs_processed_status', table_name='mes_sync_logs')
    op.drop_index('ix_mes_sync_logs_created_at', table_name='mes_sync_logs')
    op.drop_table('mes_sync_logs')
    # ### end Alembic commands ###
