"""phase2-3 add collected_videos table

Revision ID: eeb3fb42cb28
Revises: 75c7450f4406
Create Date: 2026-04-30 10:32:31.337277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eeb3fb42cb28'
down_revision: Union[str, Sequence[str], None] = '75c7450f4406'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collected_videos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('data_collection_job_id', sa.Integer(), nullable=True),
    sa.Column('recognition_log_id', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution', sa.String(length=20), nullable=True),
    sa.Column('fps', sa.Integer(), nullable=True),
    sa.Column('storage_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='collected_video_status'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], name=op.f('fk_collected_videos_camera_id_cameras'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['data_collection_job_id'], ['data_collection_jobs.id'], name=op.f('fk_collected_videos_data_collection_job_id_data_collection_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recognition_log_id'], ['recognition_logs.id'], name=op.f('fk_collected_videos_recognition_log_id_recognition_logs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_collected_videos_site_id_sites'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collected_videos'))
    )
    op.create_index('ix_collected_videos_camera_id', 'collected_videos', ['camera_id'], unique=False)
    op.create_index('ix_collected_videos_camera_recorded', 'collected_videos', ['camera_id', 'recorded_at'], unique=False)
    op.create_index('ix_collected_videos_data_collection_job_id', 'collected_videos', ['data_collection_job_id'], unique=False)
    op.create_index('ix_collected_videos_is_deleted', 'collected_videos', ['is_deleted'], unique=False)
    op.create_index('ix_collected_videos_recorded_at', 'collected_videos', ['recorded_at'], unique=False)
    op.create_index('ix_collected_videos_site_id', 'collected_videos', ['site_id'], unique=False)
    op.create_index('ix_collected_videos_status', 'collected_videos', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_collected_videos_status', table_name='collected_videos')
    op.drop_index('ix_collected_videos_site_id', table_name='collected_videos')
    op.drop_index('ix_collected_videos_recorded_at', table_name='collected_videos')
    op.drop_index('ix_collected_videos_is_deleted', table_name='collected_videos')
    op.drop_index('ix_collected_videos_data_collection_job_id', table_name='collected_videos')
    op.drop_index('ix_collected_videos_camera_recorded', table_name='collected_videos')
    op.drop_index('ix_collected_videos_camera_id', table_name='collected_videos')
    op.drop_table('collected_videos')
    # ### end Alembic commands ###
