"""phase2-3 data collection and monitoring

Revision ID: f698d7366730
Revises: 1771d1fdca57
Create Date: 2026-04-27 14:35:10.150218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f698d7366730'
down_revision: Union[str, Sequence[str], None] = '1771d1fdca57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_collection_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('job_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', 'cancelled', name='data_collection_job_status'), nullable=False),
    sa.Column('schedule_cron', sa.String(length=100), nullable=True),
    sa.Column('interval_minutes', sa.Integer(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_captured', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], name=op.f('fk_data_collection_jobs_camera_id_cameras'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_data_collection_jobs_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_data_collection_jobs_dataset_id_datasets'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_collection_jobs'))
    )
    op.create_index('ix_data_collection_jobs_camera_id', 'data_collection_jobs', ['camera_id'], unique=False)
    op.create_index('ix_data_collection_jobs_dataset_id', 'data_collection_jobs', ['dataset_id'], unique=False)
    op.create_index('ix_data_collection_jobs_is_deleted', 'data_collection_jobs', ['is_deleted'], unique=False)
    op.create_index('ix_data_collection_jobs_status', 'data_collection_jobs', ['status'], unique=False)
    op.create_table('recognition_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('labeling_task_id', sa.Integer(), nullable=True),
    sa.Column('recognition_type', sa.Enum('worker', 'helmet', 'action', 'intrusion', 'custom', name='recognition_type'), nullable=False),
    sa.Column('class_name', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('bbox', sa.JSON(), nullable=True),
    sa.Column('position_x', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('position_y', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], name=op.f('fk_recognition_logs_camera_id_cameras'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['labeling_task_id'], ['labeling_tasks.id'], name=op.f('fk_recognition_logs_labeling_task_id_labeling_tasks'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_recognition_logs_site_id_sites'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recognition_logs'))
    )
    op.create_index('ix_recognition_logs_camera_id', 'recognition_logs', ['camera_id'], unique=False)
    op.create_index('ix_recognition_logs_detected_at', 'recognition_logs', ['detected_at'], unique=False)
    op.create_index('ix_recognition_logs_labeling_task_id', 'recognition_logs', ['labeling_task_id'], unique=False)
    op.create_index('ix_recognition_logs_recognition_type', 'recognition_logs', ['recognition_type'], unique=False)
    op.create_index('ix_recognition_logs_site_id', 'recognition_logs', ['site_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_recognition_logs_site_id', table_name='recognition_logs')
    op.drop_index('ix_recognition_logs_recognition_type', table_name='recognition_logs')
    op.drop_index('ix_recognition_logs_labeling_task_id', table_name='recognition_logs')
    op.drop_index('ix_recognition_logs_detected_at', table_name='recognition_logs')
    op.drop_index('ix_recognition_logs_camera_id', table_name='recognition_logs')
    op.drop_table('recognition_logs')
    op.drop_index('ix_data_collection_jobs_status', table_name='data_collection_jobs')
    op.drop_index('ix_data_collection_jobs_is_deleted', table_name='data_collection_jobs')
    op.drop_index('ix_data_collection_jobs_dataset_id', table_name='data_collection_jobs')
    op.drop_index('ix_data_collection_jobs_camera_id', table_name='data_collection_jobs')
    op.drop_table('data_collection_jobs')
    # ### end Alembic commands ###
